### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by theintel** [fahim0864/prothomalo-epaper2pdf#1]
The new script is not working - even while running PowerShell as admin. The following error pops up:

./run.ps1 : File E:\windows7sp1\prothomalo-epaper2pdf-main\run.ps1 cannot be loaded. The file
E:\windows7sp1\prothomalo-epaper2pdf-main\run.ps1 is not digitally signed. You cannot run this script on the current
system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./run.ps1
+ ~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess`

**Comment by theintel** [comment]
My bad. I ran it without admin privileges, it worked fine.

**Comment by theintel** [comment]
Windows is not allowing the script to execute this command `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted`.
I still have to manually run this command before running the script. Is it possible to sign the script with a self-signed signature somehow?

**Comment by fahim0864** [comment]
> Windows is not allowing the script to execute this command `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted`. I still have to manually run this command before running the script. Is it possible to sign the script with a self-signed signature somehow?

you can try to sign for your machine but it's cumbersome. can you give me the output of this command `Get-ExecutionPolicy -List`

**Comment by fahim0864** [comment]
please download the new script and check the notes section. if you still encounter error, let me know

**Comment by theintel** [comment]
> > Windows is not allowing the script to execute this command `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted`. I still have to manually run this command before running the script. Is it possible to sign the script with a self-signed signature somehow?
> 
> you can try to sign for your machine but it's cumbersome. can you show me the output of this command `Get-ExecutionPolicy -List`

Here it is. I manually set the policy for LocalMachine to AllSigned.
Get-ExecutionPolicy -list

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       AllSigned

**Comment by fahim0864** [comment]
> > > Windows is not allowing the script to execute this command `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted`. I still have to manually run this command before running the script. Is it possible to sign the script with a self-signed signature somehow?
> > 
> > 
> > you can try to sign for your machine but it's cumbersome. can you show me the output of this command `Get-ExecutionPolicy -List`
> 
> Here it is. I manually set the policy for LocalMachine to AllSigned. Get-ExecutionPolicy -list
> 
> ```
>     Scope ExecutionPolicy
>     ---------------------
> ```
> 
> MachinePolicy Undefined UserPolicy Undefined Process Undefined CurrentUser Undefined LocalMachine AllSigned

Current user need to be unrestricted

**Comment by theintel** [comment]
> please download the new script and check the notes section. if you still encounter error, let me know

Although PS does not need admin rights to change execution policy for the **Process** scope, it still won't allow the script to set the policy because as it is not signed.
